name: Shop
main: net.aerulion.Shop.Main
version: 0.2
author: aerulion
depend: [Vault]
api-version: 1.13
commands:
     shop:
       description: Hiermit kann ein Shop erstellt werden.
     openshop:
       description: Hiermit kann ein Shop für einen Spieler geöffnet werden.
permissions:
     shop.use:
       description: Mit dieser Permission koennen Spieler den Shop benutzen.
       default: op
     shop.admin:
       description: Diese Permission ermoeglicht es, Admin Funktionen des Shops zu nutzen.
       default: op