name: Shop
main: net.aerulion.shop.Main
version: 1.0
author: aerulion
depend: [Nucleus, Vault]
api-version: 1.15
commands:
     shop:
       description: Hiermit kann ein Shop erstellt werden.
     openshop:
       description: Hiermit kann ein Shop für einen Spieler geöffnet werden.
permissions:
     shop.use:
       description: Mit dieser Permission koennen Spieler den Shop benutzen.
       default: op
     shop.admin:
       description: Diese Permission ermoeglicht es, Admin Funktionen des Shops zu nutzen.
       default: op